In [3]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#1 Randomization function

array([], shape=(0, 1), dtype=float64)

In [15]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random((h,w))
    B = np.random.random((h,w))
    s = A + B
    return A, B, s

operations(3, 3)


(array([[0.49378178, 0.50830386, 0.6286517 ],
        [0.07661652, 0.31233262, 0.70101993],
        [0.13474343, 0.3330313 , 0.36818291]]),
 array([[0.76416188, 0.29955028, 0.65197991],
        [0.57325298, 0.24258022, 0.38302291],
        [0.5302593 , 0.16700258, 0.93694825]]),
 array([[1.25794366, 0.80785414, 1.28063161],
        [0.6498695 , 0.55491284, 1.08404284],
        [0.66500272, 0.50003388, 1.30513116]]))

In [16]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = np.linalg.norm(A + B)

    return s

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
norm(A, B)

12.449899597988733

In [4]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    dot_product = np.dot(weights.T, inputs)
    a = np.tanh(dot_product)
    return a

inputs = np.array([1, 2])
weights = np.array([0.5, 0.5])
neural_network(inputs, weights)

0.9051482536448665

In [6]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    if x <= y:
        return x*y
    else:
        return x/y
    
scalar_function(1, 2)
scalar_function(2, 1)

2.0

In [7]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    vectorized_scalar_function = np.vectorize(scalar_function)
    return vectorized_scalar_function(x, y)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
vector_function(x, y)

array([ 4, 10, 18])

In [2]:
for i in "hello":
    print(i)

h
e
l
l
o
